"""
llm_label.py — LLM-assisted commit classifier for UVM DV failure taxonomy
Paper: "When RTL Changes, What Breaks?"
Author: Emilija Velinova

Usage:
    python3 llm_label.py --input commits.csv --output labeled_commits.csv
    python3 llm_label.py --input commits.csv --output labeled_commits.csv --validate
    python3 llm_label.py --input commits.csv --output labeled_commits.csv --limit 10

Input CSV columns required:
    commit_hash, ip_block, commit_message, rtl_diff, dv_diff

Output CSV adds:
    categories, at_risk_dv_files, justification, confidence, model, cost_usd

Requirements: requests, pandas, python-dotenv
API key:       set ANTHROPIC_API_KEY in environment or .env file
"""

import os
import json
import time
import argparse
import csv
from datetime import datetime
import requests
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

API_URL    = "https://api.anthropic.com/v1/messages"
MODEL      = "claude-haiku-4-5-20251001"
MAX_TOKENS = 600
RETRY_MAX  = 3
RETRY_WAIT = 5

PRICE_IN   = 1.00   # Haiku input  $/M tokens
PRICE_OUT  = 5.00   # Haiku output $/M tokens

# FIX 2: increased from 150 to 300 — reduces truncation-driven mislabeling
MAX_DIFF_LINES = 300

# ---------------------------------------------------------------------------
# Taxonomy
# ---------------------------------------------------------------------------

CATEGORIES = {
    "INTERFACE_DRIFT": {
        "short":      "Interface drift",
        "components": ["env_pkg", "agent", "driver", "monitor", "interface files"],
        "mechanism":  "Port width, signal name, or parameter change breaks DV component "
                      "that encodes explicit knowledge of design interface.",
        "dv_files":   ["*_env_pkg.sv", "*_if.sv", "*_agent.sv", "*_driver.sv",
                       "*_monitor.sv", "*tb_top.sv"],
    },
    "SEQUENCE_INVALIDATION": {
        "short":      "Sequence invalidation",
        "components": ["vseq", "base sequences", "sequence libraries"],
        "mechanism":  "Register map, protocol interface, or operational constraint change "
                      "renders existing UVM sequences structurally invalid.",
        "dv_files":   ["*_vseq.sv", "*_base_vseq.sv", "*_seq.sv", "*_seq_lib.sv"],
    },
    "CHECKER_DESYNC": {
        "short":      "Checker desynchronization",
        "components": ["scoreboard", "checker", "reference model"],
        "mechanism":  "RTL behavioral change (state machine, output logic, error handling) "
                      "not reflected in scoreboard reference model.",
        "dv_files":   ["*_scoreboard.sv", "*_checker.sv", "*_scb.sv", "*_ref_model.sv"],
    },
    "ASSERTION_ORPHANING": {
        "short":      "Assertion orphaning",
        "components": ["SVA bind files", "assertion interfaces", "$assertoff calls"],
        "mechanism":  "Module rename, signal removal, or hierarchy change invalidates "
                      "DV assertion reference path.",
        "dv_files":   ["*_bind.sv", "*_sva.sv", "*_assert*.sv"],
    },
    "COVERAGE_REGRESSION": {
        "short":      "Coverage regression",
        "components": ["coverage interfaces", "coverage bind files", "coverage env packages"],
        "mechanism":  "RTL change renders coverage points unreachable, vacuous, or "
                      "structurally misaligned with updated design.",
        "dv_files":   ["*_cov_if.sv", "*_cov_bind.sv", "*_cov*.sv", "*_coverage*.sv"],
    },
    "RAL_DESYNC": {
        "short":      "RAL desynchronization",
        "components": ["uvm_reg_block", "uvm_reg", "RAL model", "register package"],
        "mechanism":  "Register map change not reflected in MANUALLY MAINTAINED RAL files. "
                      "Only applies when *_reg_block.sv, *_ral_pkg.sv, or *_reg_pkg.sv "
                      "are explicitly modified in the DV diff. Do NOT assign if register "
                      "changes are only in autogenerated files or .hjson descriptions.",
        "dv_files":   ["*_reg_block.sv", "*_ral_pkg.sv", "*_reg_pkg.sv", "*_reg_model.sv"],
    },
    "OTHER": {
        "short":      "Other / infrastructure",
        "components": [],
        "mechanism":  "Change does not fit any of the above categories — tooling, "
                      "documentation, or unrelated infrastructure.",
        "dv_files":   [],
    },
}

# Ground-truth commits from Section 4
GROUND_TRUTH = [
    {
        "commit_hash":        "b058bfe507",
        "expected_categories": ["INTERFACE_DRIFT"],
        "note":               "SPI host command length 9->20 bit, env_pkg updated",
    },
    {
        "commit_hash":        "b13dc6ff8e",
        "expected_categories": ["ASSERTION_ORPHANING"],
        "note":               "I2C module rename broke $assertoff path",
    },
    {
        "commit_hash":        "da7fc3571b",
        "expected_categories": ["COVERAGE_REGRESSION"],
        "note":               "lc_flash_rma -> lc_nvm_rma rename broke cov_bind",
    },
    {
        "commit_hash":        "57f9776639",
        "expected_categories": ["CHECKER_DESYNC"],
        "note":               "entropy_src Ack SM change, scoreboard realigned",
    },
    {
        "commit_hash":        "6ee0cf0193",
        "expected_categories": ["SEQUENCE_INVALIDATION"],
        "note":               "SPI host configopts multi-register removed",
    },
]

# ---------------------------------------------------------------------------
# Prompt construction
# ---------------------------------------------------------------------------

def build_taxonomy_block() -> str:
    lines = []
    for key, cat in CATEGORIES.items():
        if key == "OTHER":
            continue
        lines.append(f"  {key}:")
        lines.append(f"    Short name : {cat['short']}")
        lines.append(f"    Mechanism  : {cat['mechanism']}")
        lines.append(f"    DV files   : {', '.join(cat['dv_files'])}")
    return "\n".join(lines)


# FIX 1: tightened RAL_DESYNC instruction added to classification rules
SYSTEM_PROMPT = f"""You are an expert UVM verification engineer specialising in
RTL co-evolution and testbench maintenance. You will analyse git commit diffs
from the OpenTitan hardware project and classify them according to a precise
taxonomy of DV (Design Verification) failure modes.

TAXONOMY OF DV FAILURE CATEGORIES
----------------------------------
{build_taxonomy_block()}

  OTHER:
    Use when the DV change is infrastructure, tooling, or does not fit above.

CLASSIFICATION RULES
--------------------
1. A commit may trigger MULTIPLE categories — assign all that apply.
2. Base your decision on the DV diff, not the RTL diff.
   The RTL diff explains WHY; the DV diff shows WHAT broke.
3. Assign confidence:
   HIGH   — file names and diff content unambiguously match the category.
   MEDIUM — strong signal but co-occurring changes make exclusive assignment hard.
   LOW    — inferred from commit message or partial diff only.
4. Identify at_risk_dv_files: list the specific DV file types affected,
   using the patterns from the taxonomy (e.g. *_scoreboard.sv, *_cov_if.sv).
5. RAL_DESYNC ONLY: assign this category if and only if the DV diff shows
   explicit changes to manually maintained RAL files (*_reg_block.sv,
   *_ral_pkg.sv, *_reg_pkg.sv). Do NOT assign RAL_DESYNC if the only
   register-related changes are in autogenerated files or sequence register
   access patterns — those are SEQUENCE_INVALIDATION instead.

OUTPUT FORMAT (strict JSON, no other text)
------------------------------------------
{{
  "categories": ["CATEGORY_1", "CATEGORY_2"],
  "at_risk_dv_files": ["pattern1", "pattern2"],
  "justification": "One or two sentences explaining the classification.",
  "confidence": "HIGH | MEDIUM | LOW"
}}
"""


def build_user_prompt(commit_hash: str, ip_block: str,
                      commit_message: str, rtl_diff: str, dv_diff: str) -> str:
    return f"""Classify this OpenTitan commit.

Commit hash : {commit_hash}
IP block    : {ip_block}
Message     : {commit_message}

RTL diff (first {MAX_DIFF_LINES} lines):
```
{_truncate_diff(rtl_diff)}
```

DV diff (first {MAX_DIFF_LINES} lines):
```
{_truncate_diff(dv_diff)}
```

Respond with JSON only."""


def _truncate_diff(diff: str) -> str:
    lines = diff.splitlines()
    if len(lines) <= MAX_DIFF_LINES:
        return diff
    kept = lines[:MAX_DIFF_LINES]
    kept.append(f"... [{len(lines) - MAX_DIFF_LINES} lines truncated]")
    return "\n".join(kept)


# ---------------------------------------------------------------------------
# API call
# ---------------------------------------------------------------------------

def call_api(system: str, user: str, api_key: str) -> dict:
    headers = {
        "x-api-key":         api_key,
        "anthropic-version": "2023-06-01",
        "content-type":      "application/json",
    }
    payload = {
        "model":      MODEL,
        "max_tokens": MAX_TOKENS,
        "system":     system,
        "messages":   [{"role": "user", "content": user}],
    }

    for attempt in range(1, RETRY_MAX + 1):
        try:
            resp = requests.post(API_URL, headers=headers,
                                 json=payload, timeout=60)
            resp.raise_for_status()
            data = resp.json()

            raw_text = data["content"][0]["text"].strip()
            if raw_text.startswith("```"):
                raw_text = raw_text.split("```")[1]
                if raw_text.startswith("json"):
                    raw_text = raw_text[4:]
            parsed = json.loads(raw_text)

            usage    = data.get("usage", {})
            in_tok   = usage.get("input_tokens",  0)
            out_tok  = usage.get("output_tokens", 0)
            cost_usd = (in_tok * PRICE_IN + out_tok * PRICE_OUT) / 1_000_000

            return {
                "result":     parsed,
                "in_tokens":  in_tok,
                "out_tokens": out_tok,
                "cost_usd":   cost_usd,
            }

        except requests.exceptions.HTTPError as e:
            status = e.response.status_code if e.response else "?"
            if status in (429, 529) and attempt < RETRY_MAX:
                wait = RETRY_WAIT * attempt
                print(f"  [rate limit {status}] waiting {wait}s (attempt {attempt})")
                time.sleep(wait)
                continue
            raise
        except (json.JSONDecodeError, KeyError) as e:
            if attempt < RETRY_MAX:
                print(f"  [parse error] retrying (attempt {attempt}): {e}")
                time.sleep(RETRY_WAIT)
                continue
            raise

    raise RuntimeError("Max retries exceeded")


# ---------------------------------------------------------------------------
# FIX 3: Resume — load already-processed hashes from existing output
# ---------------------------------------------------------------------------

def load_existing(output_path: str) -> tuple[list[dict], set[str]]:
    if not os.path.exists(output_path):
        return [], set()
    try:
        df = pd.read_csv(output_path)
        all_results = df.to_dict("records")
        # Drop ERROR rows from results — they will be retried cleanly
        results = [r for r in all_results
                   if json.loads(r["categories"])[0] != "ERROR"]
        done = set(str(r["commit_hash"]) for r in results)
        print(f"[resume] Found {len(all_results)} rows, {len(done)} successfully processed, "
              f"{len(all_results) - len(done)} ERROR rows will be retried")
        return results, done
    except Exception:
        return [], set()

# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_ground_truth(labeled_df: pd.DataFrame) -> dict:
    results = []
    for gt in GROUND_TRUTH:
        h   = gt["commit_hash"]
        row = labeled_df[labeled_df["commit_hash"].str.startswith(h)]
        if row.empty:
            results.append({
                "commit_hash": h, "status": "NOT_FOUND",
                "expected": gt["expected_categories"], "got": [],
                "note": gt["note"],
            })
            continue
        got_raw  = row.iloc[0]["categories"]
        got      = json.loads(got_raw) if isinstance(got_raw, str) else got_raw
        expected = set(gt["expected_categories"])
        match    = expected.issubset(set(got))
        results.append({
            "commit_hash": h,
            "status":      "PASS" if match else "FAIL",
            "expected":    gt["expected_categories"],
            "got":         got,
            "note":        gt["note"],
        })
    passed   = sum(1 for r in results if r["status"] == "PASS")
    total    = sum(1 for r in results if r["status"] != "NOT_FOUND")
    accuracy = passed / total if total else 0.0
    return {"accuracy": accuracy, "n_pass": passed,
            "n_total": total, "details": results}


# ---------------------------------------------------------------------------
# Cohen's kappa
# ---------------------------------------------------------------------------

def cohen_kappa(llm_labels: list, human_labels: list, all_cats: list) -> float:
    kappas = []
    for cat in all_cats:
        llm_bin   = [1 if cat in labels else 0 for labels in llm_labels]
        human_bin = [1 if cat in labels else 0 for labels in human_labels]
        n = len(llm_bin)
        if n == 0:
            continue
        po = sum(l == h for l, h in zip(llm_bin, human_bin)) / n
        pe = ((sum(llm_bin) / n) * (sum(human_bin) / n) +
              ((n - sum(llm_bin)) / n) * ((n - sum(human_bin)) / n))
        kappa = (po - pe) / (1 - pe) if pe < 1.0 else 1.0
        kappas.append(kappa)
    return sum(kappas) / len(kappas) if kappas else 0.0


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def run(input_path: str, output_path: str,
        api_key: str, limit: int = None,
        validate: bool = False, dry_run: bool = False):

    print(f"\n{'='*60}")
    print(f"  LLM Commit Classifier — {MODEL}")
    print(f"  Input  : {input_path}")
    print(f"  Output : {output_path}")
    print(f"  Diff window : {MAX_DIFF_LINES} lines per side")
    print(f"{'='*60}\n")

    df = pd.read_csv(input_path)
    required = {"commit_hash", "ip_block", "commit_message", "rtl_diff", "dv_diff"}
    missing  = required - set(df.columns)
    if missing:
        raise ValueError(f"Input CSV missing columns: {missing}")

    if limit:
        df = df.head(limit)
        print(f"[limit] Processing first {limit} commits\n")

    # FIX 3: load existing results for resume
    results, already_done = load_existing(output_path)

    total_cost    = sum(r.get("cost_usd", 0) for r in results)
    total_in_tok  = sum(r.get("in_tokens", 0) for r in results)
    total_out_tok = sum(r.get("out_tokens", 0) for r in results)
    n_total       = len(df)
    n_skipped     = 0

    for i, row in df.iterrows():
        idx   = len(results) + 1 - n_skipped
        h     = str(row["commit_hash"])
        block = str(row["ip_block"])
        msg   = str(row["commit_message"])
        rtl_d = str(row.get("rtl_diff", ""))
        dv_d  = str(row.get("dv_diff", ""))

        # Skip already processed
        if h in already_done:
            n_skipped += 1
            continue

        processed = len(results) + 1
        print(f"[{processed:>3}/{n_total}] {h[:12]} | {block:<20}",
              end=" ", flush=True)

        if dry_run:
            print("DRY RUN — skipping API call")
            results.append({
                "commit_hash":      h, "ip_block": block,
                "commit_message":   msg,
                "categories":       json.dumps(["DRY_RUN"]),
                "at_risk_dv_files": json.dumps([]),
                "justification":    "dry run", "confidence": "LOW",
                "model":            MODEL, "in_tokens": 0,
                "out_tokens":       0, "cost_usd": 0.0,
            })
            continue

        user_prompt = build_user_prompt(h, block, msg, rtl_d, dv_d)

        try:
            resp   = call_api(SYSTEM_PROMPT, user_prompt, api_key)
            parsed = resp["result"]

            categories = parsed.get("categories", ["OTHER"])
            at_risk    = parsed.get("at_risk_dv_files", [])
            justif     = parsed.get("justification", "")
            confidence = parsed.get("confidence", "LOW")

            valid_cats = [c for c in categories if c in CATEGORIES]
            if not valid_cats:
                valid_cats = ["OTHER"]

            total_cost    += resp["cost_usd"]
            total_in_tok  += resp["in_tokens"]
            total_out_tok += resp["out_tokens"]

            label_str = " | ".join(valid_cats)
            print(f"→ {label_str:<45} [{confidence}] ${resp['cost_usd']:.4f}")

            results.append({
                "commit_hash":      h, "ip_block": block,
                "commit_message":   msg,
                "categories":       json.dumps(valid_cats),
                "at_risk_dv_files": json.dumps(at_risk),
                "justification":    justif, "confidence": confidence,
                "model":            MODEL,
                "in_tokens":        resp["in_tokens"],
                "out_tokens":       resp["out_tokens"],
                "cost_usd":         resp["cost_usd"],
            })

        except Exception as e:
            print(f"ERROR: {e}")
            results.append({
                "commit_hash":      h, "ip_block": block,
                "commit_message":   msg,
                "categories":       json.dumps(["ERROR"]),
                "at_risk_dv_files": json.dumps([]),
                "justification":    str(e), "confidence": "LOW",
                "model":            MODEL, "in_tokens": 0,
                "out_tokens":       0, "cost_usd": 0.0,
            })

        # Save after every commit — protects against crashes
        out_df = pd.DataFrame(results)
        out_df.to_csv(output_path, index=False)

        time.sleep(5.0)

    # Final save
    out_df = pd.DataFrame(results)
    out_df.to_csv(output_path, index=False)

    # Summary
    print(f"\n{'='*60}")
    print(f"  SUMMARY")
    print(f"{'='*60}")
    print(f"  Commits processed : {len(results)}")
    print(f"  Tokens in         : {total_in_tok:,}")
    print(f"  Tokens out        : {total_out_tok:,}")
    print(f"  Total cost        : ${total_cost:.4f}")
    print(f"  Output saved      : {output_path}")

    from collections import Counter
    all_cats_flat = []
    for r in results:
        try:
            cats = json.loads(r["categories"])
        except Exception:
            cats = [r["categories"]]
        all_cats_flat.extend(cats)

    print(f"\n  Category distribution:")
    dist = Counter(all_cats_flat)
    for cat, count in dist.most_common():
        pct = count / len(results) * 100
        print(f"    {cat:<30} {count:>4}  ({pct:.1f}%)")

    if validate:
        print(f"\n  Ground truth validation:")
        val = validate_ground_truth(out_df)
        for d in val["details"]:
            icon = "✓" if d["status"] == "PASS" else ("?" if d["status"] == "NOT_FOUND" else "✗")
            print(f"    {icon} {d['commit_hash']} | expected {d['expected']} | got {d['got']}")
        print(f"\n  Accuracy: {val['n_pass']}/{val['n_total']} "
              f"({val['accuracy']*100:.0f}%)")

    print(f"\n{'='*60}\n")
    return out_df


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="LLM-assisted UVM DV failure classifier"
    )
    parser.add_argument("--input",       required=True)
    parser.add_argument("--output",      required=True)
    parser.add_argument("--limit",       type=int, default=None)
    parser.add_argument("--validate",    action="store_true")
    parser.add_argument("--dry-run",     action="store_true")
    parser.add_argument("--kappa-human", default=None)
    args = parser.parse_args()

    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key and not args.dry_run:
        raise EnvironmentError(
            "ANTHROPIC_API_KEY not set. "
            "Add it to your .env file or export it in your shell."
        )

    out_df = run(
        input_path  = args.input,
        output_path = args.output,
        api_key     = api_key or "",
        limit       = args.limit,
        validate    = args.validate,
        dry_run     = args.dry_run,
    )

    if args.kappa_human and not args.dry_run:
        print("Computing Cohen's kappa against human annotations...")
        human_df = pd.read_csv(args.kappa_human)
        merged   = out_df.merge(human_df, on="commit_hash",
                                suffixes=("_llm", "_human"))

        llm_labels   = [json.loads(r) for r in merged["categories_llm"]]
        human_labels = [json.loads(r) for r in merged["categories_human"]]
        all_cats     = [k for k in CATEGORIES if k != "OTHER"]

        kappa = cohen_kappa(llm_labels, human_labels, all_cats)
        print(f"\n  Cohen's kappa (LLM vs human): κ = {kappa:.3f}")
        if   kappa >= 0.80: print("  → Almost perfect agreement")
        elif kappa >= 0.60: print("  → Substantial agreement")
        elif kappa >= 0.40: print("  → Moderate agreement")
        else:               print("  → Fair/slight — review prompt and taxonomy")

        kappa_path = args.output.replace(".csv", "_kappa.json")
        with open(kappa_path, "w") as f:
            json.dump({
                "kappa":     round(kappa, 4),
                "n_commits": len(merged),
                "model":     MODEL,
                "timestamp": datetime.utcnow().isoformat(),
            }, f, indent=2)
        print(f"  Kappa result saved: {kappa_path}")


if __name__ == "__main__":
    main()